---
aqicn_key: 'e6e52e8fc683d9fcc03235abe9db9d8bc101230b'

#Allgemeine Informationen über die einzelnen Sensoren
sensor_details:
  pm25:
    name: 'lungengängiger_feinstaub'
    unit: 'µg/m3'
    description: 'Sensor gibt Informationen über den lungengängigen Feinstaub'
  pm10:
    name: 'einatembarer_feinstaub'
    unit: 'µg/m3'
    description: 'Sensor gibt Informationen über den einatembaren Feinstaub'
  o3:
    name: 'ozon'
    unit: 'µg/m3'
    description: 'Sensor gibt Informationen über den Ozongehalt'
  no2:
    name: 'stickstoffdioxid'
    unit: 'µg/m3'
    description: 'Sensor gibt Informationen über den Stickstoffdioxidgehalt'
  so2:
    name: 'schwefeldioxid'
    unit: 'µg/m3'
    description: 'Sensor gibt Informationen über den Schwefeldioxidgehalt'
  co:
    name: 'kohlenmonoxid'
    unit: 'µg/m3'
    description: 'Sensor gibt Informationen über den Kohlenstoffmonoxidgehalt'
  t:
    name: 'temperatur'
    unit: '°C'
    description: 'Sensor gibt Informationen über die Temperatur'
  p:
    name: 'pressure_luftdruck' 
    unit: 'hPa'
    description: 'Sensor gibt Informationen über den Luftdruck'
  h:
    name: 'humidity_Feuchtigkeit'  
    unit: '%'
    description: 'Sensor gibt Informationen über die Luftfeuchtigkeit'
  w:
    name: 'wind'
    unit: 'mph'
    description: 'Sensor gibt Informationen über die Windstaerke'

#Konfiguration der Heger Spezial Funktion
heger_spezial:         #Ein Wert wie _TT_TT
  taktung: 0.1
  intervall: 5          
  max_value: 1
  min_value: -1

#Konfiguration der zufälligen Städte mit ihren Sensoren
random_citys_sensors:
  taktung: 5
  anzahl_unterschiedlicher_städte: 3
  zeitlicher_abstand_zwischen_den_starts: 15
  lifetime_pro_city: 40

#Konfiguratione von Sensoren, bezogen auf eine Stadt
city_configuration:
  - wiesbaden:
    - sensor: pm25                 # lungengängiger_feinstaub
      taktung: 1          # Wiederholungsrate in s
      seed: 0             # Zu Testzwecken es kann sein, dass der Wert über mehrere Stunden gleich bleibt. So wir ncoh ein Random wert in der Range vom seed dazuaddiert auf den echten Wert addiert, damit man Veränderungen sieht (seed = 0 -> kein seed)
    - sensor: pm10                 # einatembarer_feinstaub
      taktung: 1
      seed: 0
    - sensor: o3                   #ozon
      taktung: 2
      seed: 0
    - sensor: no2                  #stickstoffdioxid
      taktung: 3
      seed: 0
    - sensor: so2                  #schwefeldioxid     
      taktung: 4
      seed: 0
    - sensor: co                   #kohlenmonoxid     
      taktung: 5
      seed: 0
    - sensor: t                    #temperatur
      taktung: 6
      seed: 0
    - sensor: p                    #pressure Luftdruck     
      taktung: 7
      seed: 0
    - sensor: h                    #humidity / Feuchtigkeit     
      taktung: 8
      seed: 0
    - sensor: w                    #wind
      taktung: 9
      seed: 0
  - berlin:
    - sensor: t                    #temperatur
      taktung: 1
      seed: 0
    - sensor: p                    #pressure Luftdruck     
      taktung: 1
      seed: 0
    - sensor: h                    #humidity / Feuchtigkeit     
      taktung: 1
      seed: 0
    - sensor: w                    #wind
      taktung: 1
      seed: 0