version: '3.8'

services:
  sensor-guard-datasim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensor-guard-datasim
    network_mode: host
    restart: always
    volumes:
      - ./config.yaml:/app/config.yaml
